"""estado y precio congelado en pedidos

Revision ID: 0c75f262417a
Revises: ded3a5067bb9
Create Date: 2026-09-14 08:41:40.800727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c75f262417a'
down_revision: Union[str, Sequence[str], None] = 'ded3a5067bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items_pedido', 'precio_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.add_column('pedidos', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('pedidos', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('pedidos', 'creado_en')
    op.alter_column('items_pedido', 'precio_unitario',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
