"""usuarios, pedidos e items

Revision ID: 285924643470
Revises: 
Create Date: 2026-08-31 08:45:46.763566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285924643470'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_table('categorias')
    op.add_column('usuarios', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('rol', sa.String(), nullable=True))
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_column('usuarios', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=True)
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'password_hash')
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categorias_pkey'))
    )
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    # ### end Alembic commands ###
