"""clase9_revocacion_baja_usuario

Revision ID: 431841480e30
Revises: 0c75f262417a
Create Date: 2026-09-14 10:26:41.468941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431841480e30'
down_revision: Union[str, Sequence[str], None] = '0c75f262417a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_baja')
    op.drop_column('usuarios', 'activo')
    # ### end Alembic commands ###
