"""clase10_imagen_url_producto

Revision ID: d97dc5d68155
Revises: 431841480e30
Create Date: 2026-09-22 13:04:43.647637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97dc5d68155'
down_revision: Union[str, Sequence[str], None] = '431841480e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'imagen_url')
    # ### end Alembic commands ###
