"""usuarios con auth

Revision ID: ded3a5067bb9
Revises: 285924643470
Create Date: 2026-09-07 09:14:48.039684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded3a5067bb9'
down_revision: Union[str, Sequence[str], None] = '285924643470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('acepto_tratamiento', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'fecha_consentimiento')
    op.drop_column('usuarios', 'acepto_tratamiento')
    op.drop_column('usuarios', 'hashed_password')
    # ### end Alembic commands ###
